
azure.cosmos.uri=https://mongo-db111.mongo.cosmos.azure.com:443/
azure.cosmos.key=121212121212
azure.cosmos.database=your-database-name
azure.cosmos.queryMetricsEnabled=true
azure.cosmos.indexMetricsEnabled=true
azure.cosmos.maxDegreeOfParallelism=4
azure.cosmos.maxBufferedItemCount=10
azure.cosmos.responseContinuationTokenLimitInKb=1
azure.cosmos.diagnosticsThresholds.pointOperationLatencyThresholdInMS=10000
azure.cosmos.diagnosticsThresholds.nonPointOperationLatencyThresholdInMS=10000
azure.cosmos.diagnosticsThresholds.requestChargeThresholdInRU=10000
azure.cosmos.diagnosticsThresholds.payloadSizeThresholdInBytes=10000

azure.cosmos.consistency-level=SESSION


# Azure storage
azure.storage.connection-string=${DB_STORAGE_URL}
azure.storage.container-name=test1


#spring.datasource.url=jdbc:mysql://localhost:3306/user-db
spring.datasource.url=${DB_CONN_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.show-sql=true

